cns_core:
  - Nature
  - Science
  - Cell
cns_subjournals:
  - Nature Communications
  - Nature Machine Intelligence
  - Nature Computational Science
  - Nature Biomedical Engineering
  - Nature Electronics
  - Nature Materials
  - npj Computational Materials
  - npj Artificial Intelligence
  - Communications Engineering
  - Science Advances
  - Science Robotics
  - Cell Reports
  - Cell Systems
  - Cell Reports Physical Science
  - iScience
